### ISSUE TITLE
General admin permissions

### ISSUE THREAD

**Issue by jdpdev** [dupersaurus/wush#36]
- [ ] (SET-MOTD) Set MOTD
- [ ] (GRANT-ADMIN) Allow granting of admin permissions (#36)
- [ ] (GRANT-BUILD) Allow granting of builder permissions (#34)
- [ ] (GRANT-MOD) Allow granting of moderator permissions (#35)
